name: project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  animated_toggle_switch: ^0.8.5
  animations: ^2.0.11
  flutter_custom_clippers: ^2.1.0
  google_fonts: ^6.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  supabase_flutter: ^2.10.3
  flutter_dotenv: ^5.2.1
  app_links: ^6.3.2
  image_picker: ^1.1.2
  file_picker: ^8.0.0+1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - .env
  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.otf
        - asset: assets/fonts/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 600

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
